version: "3"

services:
  runner:
    image: ghcr.io/bob-cd/runner
    networks:
      - bob-net
    depends_on:
      - storage
      - queue
    environment:
      BOB_STORAGE_URL: jdbc:postgresql://storage:5432/bob
      BOB_QUEUE_URL: amqp://queue:5672
    devices:
      - /dev/fuse
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
      - label=disable
    cap_add: # TODO: Remove these if possible, alternatively try rootless containerd
      - sys_admin
      - mknod

  entities:
    image: ghcr.io/bob-cd/entities
    networks:
      - bob-net
    depends_on:
      - storage
      - queue
    environment:
      BOB_STORAGE_URL: jdbc:postgresql://storage:5432/bob
      BOB_QUEUE_URL: amqp://queue:5672

  apiserver:
    image: ghcr.io/bob-cd/apiserver
    ports:
      - 7777:7777
    networks:
      - bob-net
    depends_on:
      - queue
      - storage
    environment:
      BOB_STORAGE_URL: jdbc:postgresql://storage:5432/bob
      BOB_QUEUE_URL: amqp://queue:5672

  queue:
    image: docker.io/library/rabbitmq:3-alpine
    networks:
      - bob-net
    ports:
      - 5672:5672
    volumes:
      - queuedata:/var/lib/rabbitmq/mnesia

  storage:
    image: docker.io/library/postgres:alpine
    networks:
      - bob-net
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bob
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: bob

  artifact:
    image: ghcr.io/bob-cd/artifact-local
    networks:
      - bob-net
    ports:
      - 8001:8001
    volumes:
      - artifactdata:/opt/artifacts

  resource:
    image: ghcr.io/bob-cd/resource-git
    networks:
      - bob-net
    ports:
      - 8000:8000

networks:
  bob-net:

volumes:
  pgdata:
  artifactdata:
  queuedata:
