---
apiVersion: v1
kind: Service
metadata:
  name: bob-apiserver
spec:
  type: ClusterIP
  ports:
    - port: 7777
      protocol: TCP
      targetPort: 7777
  selector:
    app: bob-apiserver

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bob-apiserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bob-apiserver
    spec:
      containers:
        - image: ghcr.io/bob-cd/apiserver
          name: bob-apiserver
          envFrom:
            - configMapRef:
                name: system-config
          ports:
            - containerPort: 7777
