---
apiVersion: v1
kind: ConfigMap
metadata:
  name: system-config
data:
  BOB_STORAGE_URL: jdbc:postgresql://bob-db:5432/bob
  BOB_QUEUE_URL: amqp://bob-queue:5672
  BOB_STREAM_URL: rabbitmq-stream://guest:guest@bob-queue:5552/%2f
