---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bob-db
spec:
  serviceName: bob-db
  selector:
    matchLabels:
      app: bob-db
  replicas: 1
  template:
    metadata:
      labels:
        app: bob-db
    spec:
      containers:
        - name: bob-db
          image: docker.io/library/nats
          args:
            - -js
          volumeMounts:
            - name: bob-db-disk
              mountPath: /tmp/nats/jetstream # change this by mounting /etc/nats/nats-server.conf if needed
  volumeClaimTemplates:
    - metadata:
        name: bob-db-disk
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: bob-db
spec:
  type: ClusterIP
  selector:
    app: bob-db
  ports:
    - port: 4222
