---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bob-queue
spec:
  serviceName: bob-queue
  selector:
    matchLabels:
      app: bob-queue
  replicas: 1
  template:
    metadata:
      labels:
        app: bob-queue
    spec:
      containers:
        - name: bob-queue
          image: rabbitmq:3-management-alpine
          command:
            - sh
          args:
            - -c
            - rabbitmq-plugins enable --offline rabbitmq_stream && rabbitmq-server
          volumeMounts:
            - name: bob-queue-disk
              mountPath: /var/lib/rabbitmq/mnesia
          env:
            RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_stream advertised_host bob-queue
  volumeClaimTemplates:
    - metadata:
        name: bob-queue-disk
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: bob-queue
spec:
  selector:
    app: bob-queue
  ports:
    - port: 5672
    - port: 5552
  clusterIP: None
