---
apiVersion: v1
kind: Service
metadata:
  name: resource-git
spec:
  ports:
    - port: 8000
  selector:
    app: resource-git
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-git
  template:
    metadata:
      labels:
        app: resource-git
    spec:
      containers:
        - image: ghcr.io/bob-cd/resource-git
          name: resource-git
          ports:
            - name: service-port
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /ping
              port: service-port
            initialDelaySeconds: 3
            periodSeconds: 3
